// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    customer_id
) VALUES ($1) RETURNING id, customer_id, created_at, updated_at
`

func (q *Queries) CreateOrder(ctx context.Context, customerID int64) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, customerID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, quantity, price_in_cents)
VALUES ($1, $2, $3, $4) RETURNING id, order_id, product_id, quantity, price_in_cents, created_at, updated_at
`

type CreateOrderItemParams struct {
	OrderID      int64 `json:"order_id"`
	ProductID    int64 `json:"product_id"`
	Quantity     int32 `json:"quantity"`
	PriceInCents int32 `json:"price_in_cents"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceInCents,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceInCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementProductStock = `-- name: DecrementProductStock :one
UPDATE products
SET quantity = quantity - $1
WHERE id = $2 AND quantity >= $1
RETURNING id, quantity
`

type DecrementProductStockParams struct {
	Quantity int32 `json:"quantity"`
	ID       int64 `json:"id"`
}

type DecrementProductStockRow struct {
	ID       int64 `json:"id"`
	Quantity int32 `json:"quantity"`
}

func (q *Queries) DecrementProductStock(ctx context.Context, arg DecrementProductStockParams) (DecrementProductStockRow, error) {
	row := q.db.QueryRow(ctx, decrementProductStock, arg.Quantity, arg.ID)
	var i DecrementProductStockRow
	err := row.Scan(&i.ID, &i.Quantity)
	return i, err
}

const findProductByID = `-- name: FindProductByID :one
SELECT id, name, price_in_cents, quantity, created_at, updated_at FROM products WHERE id = $1
`

func (q *Queries) FindProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, findProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCents,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, price_in_cents, quantity, created_at, updated_at FROM products
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCents,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
